account_id = "8f0c2f2271ff857947d9a5b2c38595a0"
compatibility_date = "2022-10-24"

main = "build/cf-ipfs.js"
name = "cf-ipfs"
workers_dev = false
route = "https://ipfs.kimlikdao.org/*"
send_metrics = false

[[kv_namespaces]]
binding = "KV"
id = "52b51a1db0ce4508a144633d407dab93"
preview_id = "836c46196848459ba8b3348e383bddf2"
